# Retrieve all categories
GET http://localhost:3000/categories

###

# Retrieve a specific category by ID
GET http://localhost:3000/categories/658eca6d5e350ccad79aea03

###

# Create a new category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "category_title": "test",
    "category_description": "test",
    "category_image": "test"
}

###

# Update an existing category by ID
POST http://localhost:3000/categories/658eca6d5e350ccad79aea03
Content-Type: application/json

{
    "category_title": "något fint",
    "category_description": "test",
    "category_image": "test"
}

###

# Delete a category by ID
DELETE http://localhost:3000/categories/658eca6d5e350ccad79aea03

###
