# Retrieve all orders
GET http://localhost:3000/app/order

###


# Retrieve a specific order by ID
GET http://localhost:3000/app/order/65a50c1ef18656f2e57d983e

###

# Create a new order
POST http://localhost:3000/app/order/create
Content-Type: application/json

{
    "user_ID": "65968c881e59c32e5d747292",
    "productList": [
      {
        "productId": "659d318c11a3361a36d55d0a",
        "quantity": 7
      },
      {
        "productId": "659d3071ff5079eaa9154a63",
        "quantity": 3
      }
    ],
    "address": {
      "city": "Frillesås",
      "country": "SE",
      "line1": "Brearedsvägen 228",
      "line2": null,
      "postal_code": "43963",
      "state": null
    },
    "shipped": false,
    "total_price": 43,
    "date": "24 mars 2024"
}

###

# Update an existing order by ID
POST http://localhost:3000/app/order/update/6596ad481c211e0a1e8a8da3
Content-Type: application/json

{
    "user_ID": "test",
    "product_ID": ["test", "test", "test"],
    "shipped": true,
    "total_price": 43,
    "date": "test"
}

###

# Delete an order by ID
DELETE http://localhost:3000/app/order/delete/65a11946fb51d54726f5ba95

###
