# Retrieve all products
GET http://localhost:3000/products

###

# Retrieve a specific product by ID
GET http://localhost:3000/products/658e9c5a5c8c58dc93b49613

###

# Create a new product
POST http://localhost:3000/create/products
Content-Type: application/json

{
  "product_title": "test",
  "product_description": "test",
  "product_image": "test",
  "product_price": 678,
  "in_stock": 2345,
  "category": ["test", "test", "test"]
}

###

# Update an existing product by ID
POST http://localhost:3000/products/update/658ea14773c205a896fbe052
Content-Type: application/json

{
  "product_title": "Smörja",
  "product_description": "mest",
  "product_image": "test",
  "product_price": 678,
  "in_stock": 2345,
  "category": ["test", "test", "test"]
}

###

# Delete a product by ID
DELETE http://localhost:3000/products/delete/658ea38a8304df9ec3a9e582

###
