
GET http://localhost:3000/user

###

GET http://localhost:3000/user/658ed29d087697c0e6d305d3

###

POST http://localhost:3000/user/auth

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "jagju",
    "password": "ofjfaeijeoinv"
}

###

POST http://localhost:3000/user/logout


###

POST http://localhost:3000/user/newuser
Content-Type: application/json

{
    "isAdmin": false,
    "email": "jag@jag.com",
    "username": "jagju",
    "password": "ofjfaeijeoinv"
}

###

POST http://localhost:3000/user/658ed29d087697c0e6d305d3
Content-Type: application/json

{
    "isAdmin": true,
    "email": "dfbgd@dfvd.com",
    "username": "linda",
    "password": "123456"
}

###

DELETE http://localhost:3000/user/65940f818173860896136e1e
